exclude: 'docs|node_modules|migrations|.git|.tox'

repos:
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
- repo: https://github.com/csachs/pyproject-flake8
  rev: v7.0.0
  hooks:
    - id: pyproject-flake8
