name: Publish

on:
  create:
    tags:
      - '*'

job:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Install poetry
        run: pip3 install poetry

      - name: Build
        run: poetry build

      - name: Configure auth
        run: poetry config pypi-token.pypi ${{ PYPI_TOKEN }}

      - name: Publish
        run: poetry publish
